hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhho
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
dddddddddddddddddddddddddddddddmNmmmddddddddddddddddddddddddddddddmmmNddddddddddddddddddddddddddddds
dddddddddddddddddddddddddddddmNMMMMMNddddddddddddddddddddddddddddMMMMMMNddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddNMMMMMMMNdddddddddddddddddddddddddddmNMMMMMMMmddddddddddddddddddddddddds
ddddddddddddddddddddddddddddmMMMMMMMMMNmmdddhhysooosyhhddddddmNNMMMMMMMMNmddddddddddddddddddddddddds
ddddddddddddddddddddddddddmNMMMNNMMMMMMMMMNdhyo//////++yhmNNMMMMMMMMMNNMMMNmddddddddddddddddddddddds
ddddddddddddddddddddddddmNMMMNdddmMMMMMMMMMMMMh////////NMMMMMMMMMMMNmddmNMMMNmddddddddddddddddddddds
ddddddddddddddddddddddmNMMMNmddddsyNMMMMMMMMMN+////////yMMMMMMMMMMNddddddmNMMMNdddddddddddddddddddds
ddddddddddddddddddddmNMMMNmdddddd+/yMMMMMMMMNho++++oosyhmNMMMMMMMNhddddddddmNMMMNdddddddddddddddddds
ddddddddddddddddddmNMMMNmdddddddd+//mMMMMMmyoosyyhhhyso+/odNMMMMMyyddddddddddmNMMMmdddddddddddddddds
ddddddddddddddddmNMMMNmdddddddddd+//ymmdyo//////+dy/:::::::+shdmm/yddddddddddddmNMMMmdddddddddddddds
ddddddddddddddmNMMMNmdddddddddddd+//////////////+dy:::::::::::://:yddddddddddddddmNMMNmdddddddddddds
ddddddddddddmNMMMNmdddddddddddddd+//////////////+dy:::::::::::::::yddddddddddddddddmMMMNmdddddddddds
dddddddddddmMMMNmdddddddddddddddd+//////////////+dh:::::::::::::::ydddddddddddddddddmNMMMNmdddddddds
dddddddddddmNNmdddddddddddddddddd+//////////////+dy:::::::::::::::ydddddddddddddddddddmNNNddddddddds
ddddddddddddddddddddddddddddddhhh+//////////////+ys:::::::::::::::shddhdddddddddddddddddddddddddddds
ddddddddddddddddddddddddddhhyyyyy+//////////////+ys:::::::::::::::syyyhdddddddddddddddddddddddddddds
ddddddddddddddddddddddddddhyyyyyy+//////////////+ys::::::::::::::/syyyyyyyyhhdddddddddddddddddddddds
ddddddddddddddddddddddddddhyyyyyyysso+//////////+yy::::::::://+ossyyyyyyyyhdddddddddddddddddddddddds
dddddddddddddddddddddddddhhhhyyyyyyyyyysso+/////+yy:::://+osyyyyyyyyyyhhhdddddddddddddddddddddddddds
dddddddddddddddddddddddddddddddhhhhhhhyyyyyyyso+oyy/+osyyyyyyyyyyyyyhhddddddddddddddddddddddddddddds
dddddddddddddddddddddddddddddddddddddhhyyyyyyyyyyhyyhyyyyyyhhhdddhddddddddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddds
