Please note that this is being sent from an anonymous email sender and replies will most likely not be read through this thread, so please send replies to antiireadyreaction@protonmail.com

Source 1: https://mathexchanges.wordpress.com/2018/06/14/why-iready-is-dangerous/
Source 2: https://dianeravitch.net/2018/06/18/mathematics-why-the-iready-assessment-is-dangerous/
Source 3: https://tultican.com/2018/06/27/iready-magnificent-marketing-terrible-teaching/
Source 4: https://www.badassteacher.org/bats-blog/i-ready-sells-50-years-old-education-failure-by-thomas-utican

On the Topic of iReady
iReady is a "teaching" program created by Curriculum Associates designed to "address every student's learning needs, accelerate growth, and enable all students to access grade-level learning". However, this description is inaccurate; the truth is far from what Curriculum Associates may have advertised. Let us imagine a reality, a reality where everything is truthful and faithful to their core functions- even the most malevolent and wicked of things. In this world, a strange world far from ours, Curriculum Associates would advertise their product as a poorly made educational software program that used the strangest of combinations to create the worst of classroom ideas. They would sell it to schools as one of mankind's worst ever creations, and some more. Now then, why is this, you ask? Surely, this program has so many benefits! It must be used in every classroom, you might say. To explain the general populace of the school's discontent with the program, we will look at the "benefits" of iReady and carefully break them apart as if they were fragile pieces of winter frost.

The Diagnostic and its Flaws
A major advertising point Curriculum Associates (curse their very name) often brings up is the reliability of the dreaded diagnostic test; the ease of use teachers supposedly have viewing their pupils progress. To be frank, this is a LIE. The diagnostic does not track progress, it instead tracks the student's boredom. A trend you may notice is the scores of students decreasing as the year sludges forward. I can assure you, if you were to ask any student- as I myself have- or any teacher for that matter, they would most likely tell you the same thing I have told you- that the scores have gone down. Furthermore, this horrid test fails to provide teachers where students specifically falter or succeed. It instead gives a rough generalization of how much boredom students are experiencing at any given time of the year. If our school was a nursing home, I would actively promote the use of this software. But our school is a place of learning, not a nursing home, is it not?

Lessons Made Not for Middle Schoolers
To start this point off, I must begin with what I think about each time I open up an iReady lesson. DOOM music blaring behind me, I thrust my fist through "Pepper Jackie"'s face with brass knuckles. I then proceed to mercilessly slaughter each of the annoying, soulless, lazily drawn characters in the lesson. Unpleasant imagery, yes, but I feel that it was needed to illustrate the thoughts many students share when opening one iReady lesson. Now then, these lessons supposedly crafted for middle school students might've been somewhat appeasing- and maybe even a little entertaining in elementary school, but we are no longer at that age. We do not find that drawn-out, mentally draining, animations will aid us in our life's complicated journies. It is a simple fact. 

Wasted Tax Money and Unhappy Parents
Maybe you've heard this hefty pricetag before, or maybe you have not. "Licenses for the i-Ready Diagnostic start at $6 per student, per subject, per year. Licenses for the combination of i-Ready Diagnostic and i-Ready instruction start at $30 per student, per subject, per year. Schools must purchase a minimum of 150 licenses." That is a large amount of money, and considering the last two points I've brought up, it seems like a bad use of it. Now, I'm not going to sit here ranting about iReady without proposing a solution. I suggest two things. Instead of iReady, we could use IXL or Kahn Academy to assist our learning. We already use IXL and it is so much more than the useless and worthless garbage that iReady is. Additionally, Kahn Academy is completely free and would save the school much more money to use on other things. My second proposal is to use the money not spent on iReady to prepare for the MCAS test. For a test that dictates so much of our year, we seem to spend very little time preparing for it in comparison. On the topic of unhappy parents, if you go to the reviews of iReady's parent company, Curriculum Associates, you will likely find very negative reviews often written by both kids and parents chastising the lack of proper communication between the parents and where their tax dollars are going to. That isn't so great, is it?

Conclusion
In conclusion, iReady is a terrible educational program that has no place in our school district or community. Please, at the very least, pass on this message or limit the use of iReady in our schools.
